export const CATEGORY_DEFINITIONS = [
  { id: 'identity', name: 'Identity', icon: 'passport' },
  { id: 'financial', name: 'Financial', icon: 'money' },
  { id: 'academic', name: 'Academic', icon: 'school' },
  { id: 'travel', name: 'Travel', icon: 'plane' },
  { id: 'embassy', name: 'Embassy', icon: 'office' },
  { id: 'conditional', name: 'Conditional', icon: 'shield' }
];

export const DOCUMENT_DATABASE = [
  {
    id: 'visa-application-form',
    title_en: 'Visa Application Form',
    title_ar: 'نموذج طلب التأشيرة',
    description_en: 'Complete the national visa application form through the e-Konsulat system and sign it in the required places.',
    description_ar: 'أكمل نموذج طلب التأشيرة الوطنية عبر نظام e-Konsulat ووقعه في الأماكن المطلوبة.',
    purpose: { en: 'Formal application submission for the Polish national visa.', ar: 'تقديم الطلب الرسمي للحصول على تأشيرة بولندا الوطنية.' },
    why_required: { en: 'The embassy requires it as the primary application document.', ar: 'تطلبه السفارة كوثيقة تقديم الطلب الأساسية.' },
    where_to_get: { en: 'Register via the official e-Konsulat portal.', ar: 'سجل عبر بوابة e-Konsulat الرسمية.' },
    notes: { en: 'The form must be signed and completed fully.', ar: 'يجب إكمال النموذج وتوقيعه بالكامل.' },
    category: 'embassy',
    priority: 'urgent',
    icon: 'document',
    google_search_query: 'Explain the Visa Application Form for Poland National Visa D Egypt',
    locations: [{ office: 'Polish Embassy Cairo', address: 'Cairo, Egypt', working_hours: 'By appointment' }]
  },
  {
    id: 'passport',
    title_en: 'Passport',
    title_ar: 'جواز السفر',
    description_en: 'A valid passport with at least two blank pages and at least three months validity after departure.',
    description_ar: 'جواز سفر ساري المفعول مع صفحتين فارغتين على الأقل وصلاحية ثلاثة أشهر على الأقل بعد المغادرة.',
    purpose: { en: 'Identity and travel document.', ar: 'وثيقة الهوية والسفر.' },
    why_required: { en: 'Required for travel and identity verification.', ar: 'مطلوب للسفر والتحقق من الهوية.' },
    where_to_get: { en: 'Egyptian Passport Authority or local passport office.', ar: 'هيئة الجوازات المصرية أو مكتب الجوازات المحلي.' },
    notes: { en: 'Ensure your passport is valid beyond the planned stay.', ar: 'تأكد من صلاحية جواز السفر بعد الإقامة المخطط لها.' },
    category: 'identity',
    priority: 'urgent',
    icon: 'passport',
    google_search_query: 'Poland National Visa D passport requirements Egypt',
    locations: [{ office: 'Egyptian Passport Office', address: 'Cairo, Egypt', working_hours: 'Mon-Fri 8:00-14:00' }]
  },
  {
    id: 'passport-copy',
    title_en: 'Passport Copy',
    title_ar: 'نسخة من جواز السفر',
    description_en: 'Submit a photocopy of the passport page with personal data and photo.',
    description_ar: 'أرسل نسخة من صفحة جواز السفر التي تحتوي على البيانات الشخصية والصورة.',
    purpose: { en: 'Supporting identity verification.', ar: 'دعم التحقق من الهوية.' },
    why_required: { en: 'The embassy needs a copy for its records.', ar: 'تحتاج السفارة إلى نسخة لسجلاتها.' },
    where_to_get: { en: 'Make copies at any print shop or office supply store.', ar: 'قم بإجراء النسخ في أي ورشة طباعة أو متجر لوازم مكتبية.' },
    notes: { en: 'Use a clear copy with complete personal details.', ar: 'استخدم نسخة واضحة تحتوي على التفاصيل الشخصية كاملة.' },
    category: 'identity',
    priority: 'high',
    icon: 'document',
    google_search_query: 'Passport copy requirements Poland visa Egypt',
    locations: [{ office: 'Copy Service', address: 'Cairo, Egypt', working_hours: 'All day' }]
  },
  {
    id: 'photo',
    title_en: 'Passport Photo',
    title_ar: 'صورة جواز سفر',
    description_en: 'Provide one recent biometric-style photo with a white background and passport dimensions.',
    description_ar: 'قدّم صورة حديثة على شكل صورة جواز سفر مع خلفية بيضاء وأبعاد مناسبة.',
    purpose: { en: 'Identity photograph for the visa file.', ar: 'صورة تعريفية لملف التأشيرة.' },
    why_required: { en: 'Required for the visa application and biometric record.', ar: 'مطلوبة لتقديم طلب التأشيرة وسجل البصمة.' },
    where_to_get: { en: 'Photo studios that provide visa-compliant photos.', ar: 'استوديوهات صور تقدم صورًا مطابقة لمتطلبات التأشيرة.' },
    notes: { en: 'The photo should be taken within the last 6 months.', ar: 'يجب أن تكون الصورة ملتقطة خلال الأشهر الستة الماضية.' },
    category: 'identity',
    priority: 'high',
    icon: 'document',
    google_search_query: 'passport photo requirements Poland visa Egypt',
    locations: [{ office: 'Visa Photo Studio', address: 'Cairo, Egypt', working_hours: 'Daily' }]
  },
  {
    id: 'previous-visas',
    title_en: 'Copies of Previous Visas',
    title_ar: 'نسخ من التأشيرات السابقة',
    description_en: 'Include copies of prior Polish or Schengen visas if you have them.',
    description_ar: 'أدرج نسخًا من التأشيرات البولندية أو الشنجن السابقة إذا كانت لديك.',
    purpose: { en: 'Show your travel history and previous visa compliance.', ar: 'إظهار تاريخ السفر والالتزام بالتأشيرات السابقة.' },
    why_required: { en: 'Helps demonstrate prior travel records.', ar: 'تساعد على إثبات سجل السفر السابق.' },
    category: 'conditional',
    priority: 'normal',
    icon: 'document',
    google_search_query: 'previous visas Poland national visa Egypt',
    locations: [{ office: 'Your archived visa documents', address: 'Home/Archive', working_hours: 'Any time' }],
    condition: { field: 'hasSchengenVisa', value: true }
  },
  {
    id: 'residence-permit',
    title_en: 'Residence Permit Copy',
    title_ar: 'نسخة من تصريح الإقامة',
    description_en: 'Non-Egyptian residents must submit a copy of their residence permit and present the original at the interview.',
    description_ar: 'يجب على المقيمين غير المصريين تقديم نسخة من تصريح الإقامة وإظهار الأصل أثناء المقابلة.',
    purpose: { en: 'Verify legal residence status in Egypt.', ar: 'التحقق من الوضع القانوني للإقامة في مصر.' },
    why_required: { en: 'Required for non-Egyptian residents.', ar: 'مطلوب للمقيمين غير المصريين.' },
    category: 'conditional',
    priority: 'high',
    icon: 'document',
    google_search_query: 'residence permit Poland visa Egypt',
    locations: [{ office: 'Immigration Office', address: 'Cairo, Egypt', working_hours: 'By appointment' }],
    condition: { field: 'nonEgyptResident', value: true }
  },
  {
    id: 'flight-reservation',
    title_en: 'Round Trip Flight Reservation',
    title_ar: 'حجز رحلة ذهاب وعودة',
    description_en: 'Provide a reservation or written oath if you have not purchased the ticket yet.',
    description_ar: 'قدّم حجزًا أو قسمًا خطيًا إذا لم تشتري التذكرة بعد.',
    purpose: { en: 'Demonstrate the intended travel dates.', ar: 'إظهار تواريخ السفر المخططة.' },
    why_required: { en: 'The embassy needs proof of intended entry and exit.', ar: 'تحتاج السفارة إلى دليل على الدخول والخروج المقصود.' },
    category: 'travel',
    priority: 'urgent',
    icon: 'plane',
    google_search_query: 'round trip flight reservation Poland visa Egypt',
    locations: [{ office: 'Airline or Travel Agency', address: 'Cairo, Egypt', working_hours: 'Daily' }]
  },
  {
    id: 'accommodation-proof',
    title_en: 'Proof of Accommodation',
    title_ar: 'دليل الإقامة',
    description_en: 'Gather proof of where you will stay in Poland such as a hotel booking or university residence confirmation.',
    description_ar: 'اجمع دليلًا على مكان الإقامة في بولندا مثل حجز فندق أو تأكيد سكن جامعي.',
    purpose: { en: 'Show where you will stay during the visit.', ar: 'إثبات مكان الإقامة أثناء الزيارة.' },
    why_required: { en: 'Required to verify lodging arrangements.', ar: 'مطلوب للتحقق من ترتيبات الإقامة.' },
    category: 'travel',
    priority: 'high',
    icon: 'office',
    google_search_query: 'accommodation proof Poland visa Egypt',
    locations: [{ office: 'Hotel or University Housing', address: 'Poland', working_hours: 'By booking' }]
  },
  {
    id: 'insurance',
    title_en: 'Travel Medical Insurance',
    title_ar: 'تأمين طبي سفر',
    description_en: 'Submit a policy covering the full stay in the Schengen area with at least EUR 30,000 coverage.',
    description_ar: 'قدّم بوليصة تغطي الإقامة بالكامل في منطقة الشنجن مع تغطية لا تقل عن 30,000 يورو.',
    purpose: { en: 'Protect against medical emergencies during the trip.', ar: 'الحماية من الطوارئ الطبية أثناء الرحلة.' },
    why_required: { en: 'Mandatory for all visa applicants.', ar: 'إلزامي لجميع المتقدمين للتأشيرة.' },
    category: 'travel',
    priority: 'urgent',
    icon: 'shield',
    google_search_query: 'travel insurance Poland visa Egypt',
    locations: [{ office: 'Insurance Provider', address: 'Cairo, Egypt', working_hours: 'Business hours' }]
  },
  {
    id: 'bank-statement',
    title_en: 'Bank Statement',
    title_ar: 'كشف حساب بنكي',
    description_en: 'Provide financial proof showing sufficient means for accommodation, travel, and living costs.',
    description_ar: 'قدّم دليلًا ماليًا يثبت وجود وسائل كافية لتغطية الإقامة والسفر والمعيشة.',
    purpose: { en: 'Demonstrate sufficient financial resources.', ar: 'إثبات توفر موارد مالية كافية.' },
    why_required: { en: 'The embassy evaluates your ability to support yourself.', ar: 'تقيم السفارة قدرتك على دعم نفسك.' },
    category: 'financial',
    priority: 'urgent',
    icon: 'money',
    google_search_query: 'bank statement Poland visa Egypt',
    locations: [{ office: 'Bank Branch', address: 'Cairo, Egypt', working_hours: 'Bank hours' }]
  },
  {
    id: 'credit-card-certificate',
    title_en: 'Credit Card Statement or Certificate',
    title_ar: 'كشف أو شهادة بطاقة ائتمان',
    description_en: 'A certificate or statement from a bank showing available credit limits may be accepted.',
    description_ar: 'يمكن قبول شهادة أو كشف من البنك يوضح حدود الائتمان المتاحة.',
    purpose: { en: 'Alternative proof of financial means.', ar: 'دليل بديل على الوسائل المالية.' },
    why_required: { en: 'Useful when bank statements are unavailable.', ar: 'مفيد عندما لا تتوفر كشوف الحساب البنكية.' },
    category: 'financial',
    priority: 'normal',
    icon: 'money',
    google_search_query: 'credit card certificate Poland visa Egypt',
    locations: [{ office: 'Bank', address: 'Cairo, Egypt', working_hours: 'Bank hours' }]
  },
  {
    id: 'sponsor-letter',
    title_en: 'Sponsor Letter and Documents',
    title_ar: 'خطاب وكيل/راعي ومستندات',
    description_en: 'If another person sponsors you, provide the sponsor letter, passport copy, employment proof, and bank statement.',
    description_ar: 'إذا كان شخص آخر راعيًا لك، قدم خطاب الراعي ونسخة من جواز السفر وإثبات العمل وكشف الحساب.',
    purpose: { en: 'Support financial sponsorship.', ar: 'دعم الكفالة المالية.' },
    why_required: { en: 'Useful when your own funds are insufficient.', ar: 'مفيد عندما لا تكون أموالك كافية.' },
    category: 'financial',
    priority: 'high',
    icon: 'document',
    google_search_query: 'sponsor document Poland visa Egypt',
    locations: [{ office: 'Sponsor Office', address: 'Cairo, Egypt', working_hours: 'Business hours' }]
  },
  {
    id: 'university-acceptance',
    title_en: 'University Acceptance Letter',
    title_ar: 'خطاب قبول جامعي',
    description_en: 'Submit the original acceptance letter or certificate of enrollment from the university.',
    description_ar: 'قدّم خطاب القبول الأصلي أو شهادة التسجيل من الجامعة.',
    purpose: { en: 'Proof of study admission.', ar: 'إثبات قبول الدراسة.' },
    why_required: { en: 'Essential for student visa applications.', ar: 'أساسي لتطبيقات تأشيرة الطالب.' },
    category: 'academic',
    priority: 'urgent',
    icon: 'school',
    google_search_query: 'university acceptance letter Poland visa Egypt',
    locations: [{ office: 'Your University Admissions Office', address: 'Egypt', working_hours: 'Office hours' }]
  },
  {
    id: 'tuition-payment-proof',
    title_en: 'Proof of Tuition Fee Payment',
    title_ar: 'دليل على دفع رسوم الدراسة',
    description_en: 'Show proof that tuition fees have been paid.',
    description_ar: 'أظهر دليلًا على دفع رسوم الدراسة.',
    purpose: { en: 'Demonstrate financial readiness for studies.', ar: 'إثبات الجاهزية المالية للدراسة.' },
    why_required: { en: 'The embassy may inspect your financial commitment.', ar: 'قد تفحص السفارة التزامك المالي.' },
    category: 'academic',
    priority: 'high',
    icon: 'money',
    google_search_query: 'tuition payment proof Poland visa Egypt',
    locations: [{ office: 'University Finance Office', address: 'Egypt', working_hours: 'Office hours' }]
  },
  {
    id: 'enrollment-certificate',
    title_en: 'Enrollment Certificate',
    title_ar: 'شهادة تسجيل',
    description_en: 'Submit an enrollment certificate from your Egyptian university or school, if applicable.',
    description_ar: 'قدّم شهادة تسجيل من جامعتك أو مدرستك المصرية، إذا كانت مطبقة.',
    purpose: { en: 'Confirm current academic status.', ar: 'تأكيد الوضع الأكاديمي الحالي.' },
    why_required: { en: 'Supports the academic purpose of your stay.', ar: 'يدعم غرض الدراسة في إقامتك.' },
    category: 'academic',
    priority: 'normal',
    icon: 'school',
    google_search_query: 'enrollment certificate Poland visa Egypt',
    locations: [{ office: 'University Registrar', address: 'Egypt', working_hours: 'Office hours' }]
  },
  {
    id: 'language-certificate',
    title_en: 'Language Proficiency Certificate',
    title_ar: 'شهادة الكفاءة اللغوية',
    description_en: 'Provide a language certificate at the level required by the host institution.',
    description_ar: 'قدّم شهادة لغة بالمستوى المطلوب من قبل المؤسسة المضيفة.',
    purpose: { en: 'Prove language readiness for study.', ar: 'إثبات الاستعداد اللغوي للدراسة.' },
    why_required: { en: 'May be required depending on your course.', ar: 'قد تكون مطلوبة حسب تخصصك.' },
    category: 'academic',
    priority: 'normal',
    icon: 'school',
    google_search_query: 'language certificate Poland visa Egypt',
    locations: [{ office: 'Language Center', address: 'Cairo, Egypt', working_hours: 'By appointment' }]
  },
  {
    id: 'minor-consent',
    title_en: 'Minor Consent Form',
    title_ar: 'نموذج موافقة قاصر',
    description_en: 'If you are under 18, provide notarized parental consent and supporting documents.',
    description_ar: 'إذا كنت قاصرًا، قدم موافقة موثقة من الوالدين ومستندات داعمة.',
    purpose: { en: 'Authorize travel for minors.', ar: 'تفويض السفر للقصر.' },
    why_required: { en: 'Required when the applicant is a minor.', ar: 'مطلوب عندما يكون المتقدم قاصرًا.' },
    category: 'conditional',
    priority: 'high',
    icon: 'document',
    google_search_query: 'minor consent Poland visa Egypt',
    locations: [{ office: 'Notary Public', address: 'Cairo, Egypt', working_hours: 'Business hours' }],
    condition: { field: 'under18', value: true }
  },
  {
    id: 'mogamma-certificate',
    title_en: 'Movement Certificate and its Translation',
    title_ar: 'شهادة التحركات وترجمتها',
    description_en: 'For first-time travellers or in case of passport loss, include a certificate covering the last 7 years.',
    description_ar: 'للمسافرين لأول مرة أو في حالة فقدان الجواز، أدرج شهادة تغطي السنوات السبع الماضية.',
    purpose: { en: 'Verify travel history when required.', ar: 'التحقق من سجل السفر عند الحاجة.' },
    why_required: { en: 'May be requested for first-time travelers.', ar: 'قد يُطلب للمسافرين لأول مرة.' },
    category: 'conditional',
    priority: 'normal',
    icon: 'document',
    google_search_query: 'Movement certificate Poland visa Egypt',
    locations: [{ office: 'Mogamma', address: 'Cairo, Egypt', working_hours: 'Office hours' }]
  }
];
